### ISSUE TITLE
The user defined cropRadius property is ignored.

### ISSUE THREAD

**Issue by alekmarinov** [kirill3333/react-avatar#26]
It's very small issue but very annoying and trivial to fix.
The cropRadius property is obscured by **const cropRadius = imgWidth / 4;** in the init() method.
For my own purposes I modified it to:
    const autoCropRadius = Math.max(this.props.minCropRadius, Math.min(imgWidth, imgHeight) / 2);
    const cropRadius = this.props.cropRadius || autoCropRadius
Also remove the respective cropRadius property from defaults as its default value is auto computed based on the image size.
Thanks for this nice component anyway!

**Comment by kirill3333** [comment]
@alekmarinov so as I understand you propose is 
- remove `cropRadius` property
- change calculation of this property to `Math.max(this.props.minCropRadius, Math.min(imgWidth, imgHeight) / 2)`

**Comment by alekmarinov** [comment]
Yes, just that:

src\avatar.jsx
-    cropRadius: 100,
+    // cropRadius: 200,

-    const cropRadius = imgWidth / 4;
+    const autoCropRadius = Math.max(this.props.minCropRadius, Math.min(imgWidth, imgHeight) / 2);
+    const cropRadius = this.props.cropRadius || autoCropRadius

**Comment by kirill3333** [comment]
@alekmarinov do you want to make PR?

**Comment by alekmarinov** [comment]
sure

**Comment by alekmarinov** [comment]
fixed by #27
