### ISSUE TITLE
It's not working on mobile

### ISSUE THREAD

**Issue by maitrid** [kirill3333/react-avatar#3]
i hope it would work properly on mobile. Is there any chance of having that soon? Thanks!

**Comment by kirill3333** [comment]
@maitrid yes I will check it on mobile. Which problems have you found and on which devices?

**Comment by maitrid** [comment]
Thank you, @kirill3333 ! 

Here're the symptoms: When using the demo page with Mobile Safari in iOS 9,10, and 11 the circular crop tool is unusable. The same problem exists for the latest Chrome on Android (as well as all older versions tested). In all cases the crop circle renders and can be moved, but any attempt to resize it results in the circle disappearing and the controls for it becoming very large (see the following screen grab). 
![image](https://user-images.githubusercontent.com/4511745/31953681-99f16d86-b8b1-11e7-8a4a-58334049261b.png)

**Comment by kirill3333** [comment]
@maitrid I've tried to fix it in version 0.5.6 (https://github.com/kirill3333/react-avatar/commit/22f3f7f8a5b42342c8f415122182f48c54b1501b)
Also I've added experimental property mobileScaleSpeed to control resize speed. By default it is 0.5
