### ISSUE TITLE
Integrating with dropzone

### ISSUE THREAD

**Issue by umershaikh97** [kirill3333/react-avatar#32]
How to use this react-avatar with dropzone ?

**Comment by kirill3333** [comment]
@umershaikh97 sorry what do you mean is `dropzone`

**Comment by kirill3333** [comment]
@umershaikh97 probably you can wrap react-avatar with https://github.com/react-dropzone/react-dropzone and pass image to react-avatar on `onDrop` callback from react-dropzone. Does it make sense?

**Comment by umershaikh97** [comment]
Thank you so much, it worked.
