### ISSUE TITLE
How to prevent file upload?

### ISSUE THREAD

**Issue by grigory-bogush** [kirill3333/react-avatar#38]
```
public onBeforeFileLoad(file) {
    // no bigger than 2mb
    if (file.size > 2*1024*1024) {
      // FIXME: Not sure how to prevent upload
      // alert('File is too big!');
    }
  }
```

**Comment by kirill3333** [comment]
@GriboryBogush, first of all, you can upload it outside the component with logic you need and provide it as an image object with `img` property

**Comment by kirill3333** [comment]
@GriboryBogush however I see your concern and will think about it.
