### ISSUE TITLE
Brokes Gatsby Build

### ISSUE THREAD

**Issue by ekremkenter** [kirill3333/react-avatar#40]
Gatsby build gives window is not defined error.

```
5:12:37 PM: error #95312 ReferenceError: window is not defined
5:12:37 PM: "window" is not available during server side rendering.
5:12:37 PM: See our docs page for more info on this error: https://gatsby.dev/debug-html
5:12:37 PM: 
5:12:37 PM:   ReferenceError: window is not defined
5:12:37 PM:   
5:12:37 PM:   - render-page.js:117315 Object../node_modules/react-avatar-edit/lib/react-avat    ar.js
5:12:37 PM:     /opt/build/repo/public/render-page.js:117315:93
5:12:37 PM:   
5:12:37 PM:   - render-page.js:30 __webpack_require__
5:12:37 PM:     /opt/build/repo/public/render-page.js:30:30
5:12:37 PM:   
5:12:37 PM:   - render-page.js:159590 Module../src/components/profile/ProfilePicture.js

```

**Comment by FilipeCovas** [comment]
same

**Comment by intra-galactic** [comment]
> Gatsby build gives window is not defined error.
> 
> ```
> 5:12:37 PM: error #95312 ReferenceError: window is not defined
> 5:12:37 PM: "window" is not available during server side rendering.
> 5:12:37 PM: See our docs page for more info on this error: https://gatsby.dev/debug-html
> 5:12:37 PM: 
> 5:12:37 PM:   ReferenceError: window is not defined
> 5:12:37 PM:   
> 5:12:37 PM:   - render-page.js:117315 Object../node_modules/react-avatar-edit/lib/react-avat    ar.js
> 5:12:37 PM:     /opt/build/repo/public/render-page.js:117315:93
> 5:12:37 PM:   
> 5:12:37 PM:   - render-page.js:30 __webpack_require__
> 5:12:37 PM:     /opt/build/repo/public/render-page.js:30:30
> 5:12:37 PM:   
> 5:12:37 PM:   - render-page.js:159590 Module../src/components/profile/ProfilePicture.js
> ```


I assume you both solved this issue, but here's an answer for curious souls. Gatsby generates static files. The issue here is Gatsby trying to render dynamic data during build. 

To fix the issue wrap dynamic content like this:

```javascript
const isBrowser = typeof window !== "undefined";

if (isBrowser) {
  // dynamic code here
}
```
