### ISSUE TITLE
Crop functionality has stopped working

### ISSUE THREAD

**Issue by ksmolyanin** [kirill3333/react-avatar#48]
I've found that moving round selection frame doesn't change crop area any more (more exactly: visually you can make the cropping area smaller but after saving image is not cropped).

I guess that it is caused by update of some library from dependency list of your component.

**Comment by kirill3333** [comment]
@ksmolyanin can you provide an example?

**Comment by ksmolyanin** [comment]
I do not use the component any more, so can't provide the steps. Sorry.
