### ISSUE TITLE
react-dom.development.js:13891 Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/avatar.b9414da5.jsx') is not a valid name.

### ISSUE THREAD

**Issue by dipak-techniexe** [kirill3333/react-avatar#5]
Get this issue when i am using typescript.

react-dom.development.js:13891 Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/avatar.b9414da5.jsx') is not a valid name.

**Comment by kirill3333** [comment]
@dipak-techniexe could you provide your webpack config and package.json ?

**Comment by kirill3333** [comment]
@dipak-techniexe could you try last version 0.5.8 where I've added prebuilded version

**Comment by kirill3333** [comment]
#4 fixed
