### ISSUE TITLE
Vertical images not working

### ISSUE THREAD

**Issue by spiri91** [kirill3333/react-avatar#50]

**Comment by maxxafari** [comment]
Same issue. When uploading a photo from a mobile device that is taken with the camera rotated 90deg "vertical video syndrome". The metadata of the image tells the browser to rotate it. But when the preview is created the rotation is not taken to consideration. Could not recreate the issue on the desktop with the same picture. tested in chrome android.

**Comment by Nizebulous** [comment]
Seeing the same issue on my Desktop.

**Comment by haukened** [comment]
Same problem here. Anyone find a solution to this yet? This really has a great touch enabled UI but the rotation issue on the preview ruins it.

**Comment by haukened** [comment]
This is the same as #21 and is addressed by my recent PR #56

**Comment by kirill3333** [comment]
@spiri91 @Nizebulous fixed in 0.9.0 release

**Comment by Nizebulous** [comment]
@kirill3333 I'm still experiencing this issue with 0.9.0.
