### ISSUE TITLE
Customize borderStyle and labelStyle

### ISSUE THREAD

**Issue by qqdaiyu55** [kirill3333/react-avatar#7]
Could you plz update the component to make borderStyle and labelStyle customizable?
Now I have to modify them in `/lib/react-avatar.js` manually.

**Comment by kirill3333** [comment]
@qqdaiyu55 try this https://github.com/kirill3333/react-avatar/releases/latest

**Comment by qqdaiyu55** [comment]
@kirill3333 Thank you! It works.
