### ISSUE TITLE
Option to have a square / rectangular crop area ?

### ISSUE THREAD

**Issue by kdgit1** [kirill3333/react-avatar#8]
This looks great. Is there an easy way to have a rectangular / square cropType option as well ? 
Thanks.

**Comment by kirill3333** [comment]
@kdgit1 I am thinking about it. Probably after new year holidays I will implement this functionality

**Comment by elocke** [comment]
+1

**Comment by daminufe** [comment]
Isn't that the `cropRadius` prop?

**Comment by kirill3333** [comment]
@neomrc could you provide a working example? I tried and from my point of view, it is not just a crop radius setting.

**Comment by neomrc** [comment]
@kirill3333 what I mean is the `cropRadius` prop is not an option for making the photo cropper selector **rectangle**

**Comment by tuanhuu** [comment]
Any update with square avatar option ?

**Comment by tuanhuu** [comment]
> @kirill3333 what I mean is the `cropRadius` prop is not an option for making the photo cropper selector **rectangle**

cropRadius mean size of circle, not border-radius of image

**Comment by jason2li** [comment]
Is this still being considered?  I would like this feature as well.

**Comment by ladislavjacho** [comment]
@kirill3333 @neomrc @jason2li  did anybody figured it out? thank you for any updates in this topic

**Comment by foxylion** [comment]
@kirill3333 The PR #60 might partially fix this issue.
