### ISSUE TITLE
get image URL

### ISSUE THREAD

**Issue by Hulxv** [kirill3333/react-avatar#81]
How can get an image URL after cropping?

when I use onCrop attribute it returns an empty string, How can I fix that?

My Code :
`
<EditAvatar
	width={390}
	height={295}
	src={'https://pbs.twimg.com/profile_images/776714243173474304/ByDDFCvI_400x400.jpg'}
        onCrop={(preview) => {
	        console.log('img =>', preview)  
                console.log('img type =>',typeof preview)  
        }}
/>
`

result:
`
img =>
img type => string
`

and this warning:
`Konva warning: Unable to get data URL. Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.`

**Comment by kirill3333** [comment]
@Hulxv onCrop returns base64 string - it is croped image

**Comment by andreasglarakis** [comment]
I have the same error. The problem is that the string is empty, do I have to use it differently?
