### ISSUE TITLE
Allow completely custom button style

### ISSUE THREAD

**Issue by augustkimo** [kirill3333/react-avatar#82]
It would be nice if you could send in a HTML button as a prop (with a pre-specified `onClick` action maybe) so that the UI can be more controllable as the given UI may not fit a given design too good. The package is great thanks.

Ex, how I would have my button look:
![ex1](https://user-images.githubusercontent.com/72067396/135868164-d2f84c34-d229-4025-8008-462b4c38a7f8.PNG)
![ex2](https://user-images.githubusercontent.com/72067396/135868161-99d92772-6e39-416f-ace7-27323f123717.PNG)
^How the package makes my button look:

**Comment by kirill3333** [comment]
@augustkimo you can use this property 

https://github.com/kirill3333/react-avatar/blob/master/src/avatar.jsx#L502

`borderStyle`

check ReadMe for more details
